/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/SXKa2wTutHJ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"
import { Checkbox } from "@/components/ui/checkbox"
import { Label } from "@/components/ui/label"
import { Button } from "@/components/ui/button"

const MEDIA = ['print', 'painting', 'sculpture', 'mixed-media', 'photography', 'drawing']
const GENRES = ['American', 'European', 'Latin American', 'Asian', 'Contemporary']


export function CatalogueSearch() {
  return (
    <div className="w-full max-w-6xl mx-auto grid lg:grid-cols-[300px_1fr] gap-6">
      <div className="bg-white dark:bg-gray-950 rounded-lg shadow-lg p-6 space-y-6 lg:sticky lg:top-6">
        <div className="flex items-center space-x-4">
          <SearchIcon className="h-5 w-5 text-gray-500 dark:text-gray-400" />
          <Input
            className="flex-1 bg-transparent border-none focus:ring-0 text-gray-900 dark:text-gray-50 placeholder-gray-500 dark:placeholder-gray-400"
            placeholder="Search by artist"
            type="text"
          />
        </div>
        <div className="space-y-4">
          <div>
            <h3 className="text-sm font-semibold text-gray-900 dark:text-gray-50 mb-2">Search by Genre</h3>
            <div className="space-y-2">
              {GENRES.map((genre) => (
                <div key={genre} className="flex items-center space-x-2">
                  <Checkbox id={genre} />
                  <Label className="text-gray-500 dark:text-gray-400 font-medium" htmlFor={genre}>
                    {genre}
                  </Label>
                </div>
              ))}
            </div>
          </div>
          <div>
            <h3 className="text-sm font-semibold text-gray-900 dark:text-gray-50 mb-2">Search by Media</h3>
            <div className="space-y-2">
              {MEDIA.map((medium) => (
                <div key={medium} className="flex items-center space-x-2">
                  <Checkbox id={medium} />
                  <Label className="text-gray-500 dark:text-gray-400 font-medium" htmlFor={medium}>
                    {medium}
                  </Label>
                </div>
              ))}
            </div>
          </div>
          <Button variant="outline">Search</Button>
        </div>
      </div>
      <div className="bg-white dark:bg-gray-950 rounded-lg shadow-lg p-6 space-y-6">
        <div className="flex items-center space-x-4 lg:hidden">
          <SearchIcon className="h-5 w-5 text-gray-500 dark:text-gray-400" />
          <Input
            className="flex-1 bg-transparent border-none focus:ring-0 text-gray-900 dark:text-gray-50 placeholder-gray-500 dark:placeholder-gray-400"
            placeholder="Search cards..."
            type="text"
          />
          <Button className="ml-auto" size="icon" variant="ghost">
            <FilterIcon className="h-5 w-5" />
            <span className="sr-only">Toggle filters</span>
          </Button>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          <div className="bg-white dark:bg-gray-900 rounded-lg shadow-lg overflow-hidden">
            <img
              alt="Card Image"
              className="w-full h-48 object-cover"
              height={250}
              src="/placeholder.svg"
              style={{
                aspectRatio: "400/250",
                objectFit: "cover",
              }}
              width={400}
            />
            <div className="p-4 space-y-2">
              <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-50">Card Title</h3>
              <p className="text-gray-500 dark:text-gray-400 line-clamp-2">
                This is a description of the card. It can be a bit longer and will be truncated after two lines.
              </p>
            </div>
          </div>
          <div className="bg-white dark:bg-gray-900 rounded-lg shadow-lg overflow-hidden">
            <img
              alt="Card Image"
              className="w-full h-48 object-cover"
              height={250}
              src="/placeholder.svg"
              style={{
                aspectRatio: "400/250",
                objectFit: "cover",
              }}
              width={400}
            />
            <div className="p-4 space-y-2">
              <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-50">Another Card</h3>
              <p className="text-gray-500 dark:text-gray-400 line-clamp-2">
                This is another card description that is a bit longer to showcase the truncation.
              </p>
            </div>
          </div>
          <div className="bg-white dark:bg-gray-900 rounded-lg shadow-lg overflow-hidden">
            <img
              alt="Card Image"
              className="w-full h-48 object-cover"
              height={250}
              src="/placeholder.svg"
              style={{
                aspectRatio: "400/250",
                objectFit: "cover",
              }}
              width={400}
            />
            <div className="p-4 space-y-2">
              <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-50">Third Card</h3>
              <p className="text-gray-500 dark:text-gray-400 line-clamp-2">
                This is the third card description, also with a bit more text to demonstrate the truncation.
              </p>
            </div>
          </div>
          <div className="bg-white dark:bg-gray-900 rounded-lg shadow-lg overflow-hidden">
            <img
              alt="Card Image"
              className="w-full h-48 object-cover"
              height={250}
              src="/placeholder.svg"
              style={{
                aspectRatio: "400/250",
                objectFit: "cover",
              }}
              width={400}
            />
            <div className="p-4 space-y-2">
              <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-50">Fourth Card</h3>
              <p className="text-gray-500 dark:text-gray-400 line-clamp-2">
                This is the fourth card description, also with a bit more text to demonstrate the truncation.
              </p>
            </div>
          </div>
          <div className="bg-white dark:bg-gray-900 rounded-lg shadow-lg overflow-hidden">
            <img
              alt="Card Image"
              className="w-full h-48 object-cover"
              height={250}
              src="/placeholder.svg"
              style={{
                aspectRatio: "400/250",
                objectFit: "cover",
              }}
              width={400}
            />
            <div className="p-4 space-y-2">
              <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-50">Fifth Card</h3>
              <p className="text-gray-500 dark:text-gray-400 line-clamp-2">
                This is the fifth card description, also with a bit more text to demonstrate the truncation.
              </p>
            </div>
          </div>
          <div className="bg-white dark:bg-gray-900 rounded-lg shadow-lg overflow-hidden">
            <img
              alt="Card Image"
              className="w-full h-48 object-cover"
              height={250}
              src="/placeholder.svg"
              style={{
                aspectRatio: "400/250",
                objectFit: "cover",
              }}
              width={400}
            />
            <div className="p-4 space-y-2">
              <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-50">Sixth Card</h3>
              <p className="text-gray-500 dark:text-gray-400 line-clamp-2">
                This is the sixth card description, also with a bit more text to demonstrate the truncation.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

function FilterIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3" />
    </svg>
  )
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}
